export default {
  code: "en",
  messages: {
    required: "{field} is required",
    email: "email is invalid",
    min: "{field} must contain minimum 0:{min} characters",
    max: "{field} must contain maximum 0:{min} characters",
    georgian_text: "{field} must contain georgian characters",
    confirmed: "{field} field does not match",
    lowercase: "{field} must contain lowercase characters",
    english_text: "{field} must contain english characters",
  },
  names: {
    username: "username",
    email: "email",
    password: "password",
    password_confirmation: "password confirmation",
    movie_name_en: "movie name",
    movie_name_ka: "movie name",
    director_name_en: "director name",
    director_name_ka: "director name",
    year: "year",
    budget: "budget",
    movie_description_en: "movie description",
    movie_description_ka: "movie description",
    movie_picture: "movie picture",
    quote_en: "quote",
    quote_ka: "quote",
    quote_picture: "quote picture",
  },
};
