export default {
  code: "ka",
  messages: {
    required: "გთხოვთ შეავსოთ მოცემული ველი",
    email: "თქვენს მიერ შეყვანილი ტექსტი არ აკმაყოფილებს მეილის ფორმატს",
    min: "{field} უნდა შეიცავდეს მინიმუმ 0:{min} სიმბოლოს",
    max: "{field} უნდა შეიცავდეს მაქსიმუმ 0:{min} სიმბოლოს",
    georgian_text: "გთხოვთ {field} შეიყვანეთ ქართული სიმბოლოებით",
    confirmed: "{field} არ ემთხვევა",
    lowercase: "{field} უნდა შეიცავდეს პატარა ასოებს",
    english_text: "გთხოვთ {field} შეიყვანეთ ინგლისური სიმბოლოებით",
  },
  names: {
    username: "მომხმარებლის სახელი",
    email: "ელ-ფოსტა",
    password: "პაროლი",
    password_confirmation: "პაროლის დადასტურება",
    movie_name_en: "ფილმის სახელი",
    movie_name_ka: "ფილმის სახელი",
    director_name_en: "რეჟისორის სახელი",
    director_name_ka: "რეჟისორის სახელი",
    year: "წელი",
    budget: "ბიუჯეტი",
    movie_description_en: "ფილმის აღწერა",
    movie_description_ka: "ფილმის აღწერა",
    movie_picture: "ფილმის სურათი",
    quote_en: "ციტატა",
    quote_ka: "ციტატა",
    quote_picture: "ციტატის სურათი",
  },
};
